import { stateConst } from "./StateConst";

export const stateAccounts = {
  countAllPosts: 0,
  myId: "_serhii_007_",
  accounts: [
    {
      id: "_serhii_007_",
      name: "Serhii Cherkashen",
      profilePhoto:
        "https://img8.eadaily.com/r650x400/o/7ab/90ba0d43a1639d2b94b161ef6331b.jpeg",
      mySubscriptions: ["_messi_", "_messi_", "_messi_"],
      myFollowers: ["qqq"],
      stories: [],
      posts: [
        {
          id: "_serhii_007_1",
          image:
            "https://i.stopcor.org/person/2022/4/9/vladimirzelenskij51939489510.jpeg?size=1000x1000",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "_serhii_007_2",
          image:
            "https://www.gazeta.uz/media/img/2022/02/YRnXBo16454963010062_b.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "_serhii_007_3",
          image:
            "https://api.delfi.lt/media-api-image-cropper/v1/ff5f7b13-6084-4558-9e82-e01b31426455.jpg?noup&w=1200&h=711&ch=0.7958&cw=1&cx=0&cy=0.0292&r=16:9&fx=0.5&fy=0.25",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "_serhii_007_4",
          image:
            "https://www.rbc.ua/static/img/3/j/3j0a8672_id54881_650x410_4_1200x675.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "_serhii_007_5",
          image:
            "https://s.ura.news/760/images/news/upload/news/703/883/1052703883/807222_Vladimir_Zelenskiy_stock_zelenskiy_vladimir_stock_250x0_1042.696.0.0.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
      ],
      savePosts: [
        // {
        //   accountId: "leomessi",
        //   postId: "leomessi2",
        // },
        {
          accountId: "ufc",
          postId: "ufc1",
        },
        {
          accountId: "azov.media",
          postId: "azov.media3",
        },
      ],
    },
    {
      id: "leomessi",
      name: "Leo Messi",
      profilePhoto:
        "https://elplanetaurbano.com/wp-content/uploads/2022/12/messi-record-instagram-planeta-urbano-01.jpg",
      mySubscriptions: ["asd", "qwerty", "lsd"],
      myFollowers: ["qqq"],
      stories: [],
      posts: [
        {
          id: "leomessi1",
          image:
            "https://cdn.britannica.com/35/238335-050-2CB2EB8A/Lionel-Messi-Argentina-Netherlands-World-Cup-Qatar-2022.jpg",
          text: "asd",
          // likes: 10,
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi2",
          image: "https://fcb-abj-pre.s3.amazonaws.com/img/jugadors/MESSI.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa", "_serhii_007_"],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi3",
          image:
            "https://ca-times.brightspotcdn.com/dims4/default/4ab4d0e/2147483647/strip/true/crop/4403x2935+4+0/resize/2400x1600!/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2Fc3%2Fe0%2F67e70e054fb6a951343e1e918eff%2Fhttps-delivery-gettyimages.com%2Fdownloads%2F1597782801",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi4",
          status: "video",
          poster: stateConst.image.all.poster,
          video: stateConst.video.video,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi5",
          image:
            "https://womanel.com/wp-content/uploads/2019/10/adidas-lionel-messi-15-years-nemeziz-sneakers-04.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi6",
          image:
            "https://pbs.twimg.com/media/Fh_SxWdWQAE_6Xc?format=jpg&name=large",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi7",
          image:
            "https://img.championat.com/c/900x900/news/big/t/k/messi-nejmar-i-mbappe-predstavili-novuyu-formu-pszh-na-sezon-2023-2024_16855215901254834938.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi8",
          image: "https://prsport.net/upload/meshokong11.jpeg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi9",
          image:
            "https://img.championat.com/s/732x488/news/big/a/p/zolotoj-mjach-dostalsja-messi_15753549291177356384.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "leomessi10",
          image:
            "https://isport.ua/i/73/37/00/1/7337001/image_main/43109c2bce462e6c7751d96dbfdb3ae1-quality_70Xresize_1Xallow_enlarge_0Xw_835Xh_0.jpg",
          text: "asd",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        //
        // testStateVideo: [
        //   {
        //     id: "video1",
        //     video: stateConst.video.video,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video2",
        //     video: stateConst.video.motoVideo,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video3",
        //     video: stateConst.video.video,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video4",
        //     video: stateConst.video.motoVideo2,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video5",
        //     video: stateConst.video.motoVideo3,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video6",
        //     video: stateConst.video.motoVideo4,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video7",
        //     video: stateConst.video.motoVideo5,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video8",
        //     video: stateConst.video.motoVideo6,
        //     muted: true,
        //     autoplay: false,
        //   },
        //   {
        //     id: "video9",
        //     video: stateConst.video.motoVideo7,
        //     muted: true,
        //     autoplay: false,
        //   },
        // ],
        //
      ],
    },
    {
      id: "motoCross",
      name: "Moto My Life",
      profilePhoto:
        "https://www.shutterstock.com/image-vector/vector-motocross-rider-on-motorcycle-600w-2290016003.jpg",
      mySubscriptions: ["asd", "qwerty", "lsd"],
      myFollowers: ["qqq"],
      stories: [],
      posts: [
        {
          id: "motoCross1",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.video,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "motoCross2",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "motoCross3",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo2,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        //
        {
          id: "motoCross4",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo3,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "motoCross5",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo4,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "motoCross6",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo5,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "motoCross7",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo6,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
        {
          id: "motoCross8",
          status: "video",
          poster: stateConst.image.all.posterMoto2,
          video: stateConst.video.motoVideo7,
          muted: true,
          autoplay: false,
          text: "asd Video",
          likesss: 0,
          likes: [],
          comments: 3,
          save: 2,
        },
      ],
    },
    {
      id: "ufc",
      name: "UFC",
      profilePhoto:
        "https://play-lh.googleusercontent.com/RAd9B7xcEckaTwiTYBE95p3Qk6qjm77XIm8fOuKViWTyd2N9DZVcQDtvHkB3AmCMiVYm",
      mySubscriptions: ["asd", "qwerty", "lsd"],
      myFollowers: ["qqq"],
      stories: [],
      posts: [
        {
          id: "ufc1",
          image:
            "https://i.guim.co.uk/img/media/0f786c915e12366d53dd9e60a7c48d19ebde103a/0_148_5879_3529/master/5879.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=97e332f0321dc8f44ad6ec4ec54fa0d4",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc2",
          image:
            "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2021-07/MCGREGOR_CONOR_L_07-10.png?itok=xbg9Kwfj",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc3",
          image:
            "https://lh3.googleusercontent.com/proxy/oS966T5xVupypEInjat1ifdwkeDjkvpwn9_QEsjzXQ8zwX-IFxs69OGiqmBUaZxohXrNAd_aQy5eqvkpik5iEY9DtGWrAqm587Lfuk-eT9e9x5TCQllt26czwbSvXQcMUjxVRQ7i3lQw0h4IsiIUOa_WqTs5nH-Pb_vBgKXSYg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc4",
          image:
            "https://img.championat.com/c/900x900/news/big/q/a/konor-makgregor-nameknul-v-kakom-divizione-ufc-planiruet-vystupat_1667901172455704574.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc5",
          image: "https://www.sostav.ru/images/news/2019/02/07/mv0qemcy.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc6",
          image:
            "https://valetudo.ru/images/stories/grey_187/grey_187_2/mcgregor_money_1_new.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc7",
          image:
            "https://img.prosports.kz/news/content/201017_7e362113cea37c895304ba42e1a72d6b.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc8",
          image: "https://biographe.ru/wp-content/uploads/2021/07/542412.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc9",
          image:
            "https://www.russianireland.com/wp-content/uploads/2021/04/McGreggor-Proper-e1617783962624.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "ufc8",
          image:
            "https://cdn.segodnya.ua/i/original/media/image/5e2/1df/68c/5e21df68c3b01.jpg.webp",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
      ],
    },
    {
      id: "azov.media",
      name: "AZOV",
      profilePhoto:
        "https://yt3.googleusercontent.com/34y5URTIVIX-OpndRZb8jDhKZhi_m1TFbq4xLQDlwrz7fxNRphVJQXFNvPHoh_hY7uiwLxALIA=s900-c-k-c0x00ffffff-no-rj",
      mySubscriptions: ["asd", "qwerty", "lsd"],
      myFollowers: ["qqq"],
      stories: [],
      posts: [
        {
          id: "azov.media1",
          image:
            "https://tenti.in.ua/catalog/wp-content/uploads/2022/12/flah-voyn-vsu-azov1.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media2",
          image:
            "https://i.eurosport.com/2023/11/12/3824703-77726988-2560-1440.jpg",
          text: "azov",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media3",
          image:
            "https://tenti.in.ua/catalog/wp-content/uploads/2022/06/flag-polka-azov-geroyam-slava..jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media4",
          image:
            "https://www.thenation.com/wp-content/uploads/2023/06/Golinkin-Azov-ftr-680x430.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media5",
          image:
            "https://static.ukrinform.com/photos/2018_08/thumb_files/630_360_1533127461-4038.jpeg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media6",
          image:
            "https://tenti.in.ua/catalog/wp-content/uploads/2023/05/prapor-azov-zhovtyi.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media7",
          image:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/AZOV_Logo_%28SSO_Kyiv%29.svg/1089px-AZOV_Logo_%28SSO_Kyiv%29.svg.png",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media8",
          image:
            "https://tenti.in.ua/catalog/wp-content/uploads/2022/12/flah-polka-azov.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media9",
          image:
            "https://www.wsws.org/asset/4dda9b76-f63a-479c-854f-a6f353aa17bb?rendition=1600x900",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media10",
          image:
            "https://armyinform.com.ua/wp-content/uploads/2024/02/b9c293db-40fc-44f8-b7ad-18568af63b2d.jpeg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media11",
          image:
            "https://detector.media/doc/images/news/archive/2021/199034/i75_ArticleImage_199034.webp",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media12",
          image:
            "https://www.5.ua/media/pictures/original/262564.jpg?t=1674763443",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media13",
          image: "https://i.lb.ua/096/20/6272d5514e7eb.jpeg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media14",
          image:
            "https://cdn4.suspilne.media/images/resize/720x1.78/01943427d1ab381e.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media15",
          image:
            "https://cdn.cases.media/image/wide/405b16eb-fa71-4bf5-a4ec-59b5ea65bd79.png",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        {
          id: "azov.media16",
          image: "https://images.prom.ua/4217062685_shevron-azov-9.jpg",
          text: "asd",
          likesss: 123,
          likes: ["asd", " qwerty", " aaa"],
          comments: 3,
          save: 2,
        },
        // {
        //   image: "http",
        //   text: "asd",
        //   likes: 10,
        //   comments: 3,
        //   save: 2,
        // },
      ],
    },
    // {
    //   id: "therock",
    //   name: "Dwayne Johnson",
    //   profilePhoto:
    //     "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Dwayne_Johnson_2%2C_2013.jpg/279px-Dwayne_Johnson_2%2C_2013.jpg",
    //   mySubscriptions: ["asd", "qwerty", "lsd"],
    //   myFollowers: ["qqq"],
    //   stories: [],
    //   posts: [
    //     {
    //       image:
    //         "https://images.delfi.ee/media-api-image-cropper/v1/1d2bbff0-f3b5-11ed-bac7-b7ede865fd69.jpg?noup&w=1200&h=711",
    //       text: "asd",
    //       likesss: 123,
    //       likes: ["asd", " qwerty", " aaa"],
    //       comments: 3,
    //       save: 2,
    //     },
    //     {
    //       image:
    //         "https://afisha.bigmir.net/i/54/73/26/8/5473268/image_main/9708fd294f3b92b5ddef196c38c2ce9d-quality_75Xresize_crop_1Xallow_enlarge_0Xw_790Xh_445.jpg",
    //       text: "asd",
    //       likesss: 123,
    //       likes: ["asd", " qwerty", " aaa"],
    //       comments: 3,
    //       save: 2,
    //     },
    //     {
    //       image: "https://www.mzk2.ru/wp-content/uploads/2019/11/skala-2.jpg",
    //       text: "asd",
    //       likesss: 123,
    //       likes: ["asd", " qwerty", " aaa"],
    //       comments: 3,
    //       save: 2,
    //     },

    //     // {
    //     //   image: "http",
    //     //   text: "asd",
    //     //   likes: 10,
    //     //   comments: 3,
    //     //   save: 2,
    //     // },
    //   ],
    // },
    // {},
    // {},
  ],
  currentAccount: {
    id: "azov.media",
    name: "AZOV",
    profilePhoto:
      "https://yt3.googleusercontent.com/34y5URTIVIX-OpndRZb8jDhKZhi_m1TFbq4xLQDlwrz7fxNRphVJQXFNvPHoh_hY7uiwLxALIA=s900-c-k-c0x00ffffff-no-rj",
    mySubscriptions: ["asd", "qwerty", "lsd"],
    myFollowers: ["qqq"],
    stories: [],
    posts: [
      {
        id: "azov.media1",
        image:
          "https://tenti.in.ua/catalog/wp-content/uploads/2022/12/flah-voyn-vsu-azov1.jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media2",
        image:
          "https://i.eurosport.com/2023/11/12/3824703-77726988-2560-1440.jpg",
        text: "azov",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media3",
        image:
          "https://tenti.in.ua/catalog/wp-content/uploads/2022/06/flag-polka-azov-geroyam-slava..jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media4",
        image:
          "https://www.thenation.com/wp-content/uploads/2023/06/Golinkin-Azov-ftr-680x430.jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media5",
        image:
          "https://static.ukrinform.com/photos/2018_08/thumb_files/630_360_1533127461-4038.jpeg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media6",
        image:
          "https://tenti.in.ua/catalog/wp-content/uploads/2023/05/prapor-azov-zhovtyi.jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media7",
        image:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/AZOV_Logo_%28SSO_Kyiv%29.svg/1089px-AZOV_Logo_%28SSO_Kyiv%29.svg.png",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media8",
        image:
          "https://tenti.in.ua/catalog/wp-content/uploads/2022/12/flah-polka-azov.jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media9",
        image:
          "https://www.wsws.org/asset/4dda9b76-f63a-479c-854f-a6f353aa17bb?rendition=1600x900",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media10",
        image:
          "https://armyinform.com.ua/wp-content/uploads/2024/02/b9c293db-40fc-44f8-b7ad-18568af63b2d.jpeg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media11",
        image:
          "https://detector.media/doc/images/news/archive/2021/199034/i75_ArticleImage_199034.webp",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media12",
        image:
          "https://www.5.ua/media/pictures/original/262564.jpg?t=1674763443",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media13",
        image: "https://i.lb.ua/096/20/6272d5514e7eb.jpeg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media14",
        image:
          "https://cdn4.suspilne.media/images/resize/720x1.78/01943427d1ab381e.jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media15",
        image:
          "https://cdn.cases.media/image/wide/405b16eb-fa71-4bf5-a4ec-59b5ea65bd79.png",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      {
        id: "azov.media16",
        image: "https://images.prom.ua/4217062685_shevron-azov-9.jpg",
        text: "asd",
        likesss: 123,
        likes: ["asd", " qwerty", " aaa"],
        comments: 3,
        save: 2,
      },
      // {
      //   image: "http",
      //   text: "asd",
      //   likes: 10,
      //   comments: 3,
      //   save: 2,
      // },
    ],
  },
  // myAccount: {
  //   id: "_serhii_007_",
  //   name: "Serhii Cherkashen",
  //   profilePhoto:
  //     "https://img8.eadaily.com/r650x400/o/7ab/90ba0d43a1639d2b94b161ef6331b.jpeg",
  //   mySubscriptions: ["_messi_", "_messi_", "_messi_"],
  //   myFollowers: ["qqq"],
  //   stories: [],
  //   posts: [
  //     {
  //       id: "leomessi1",
  //       image:
  //         "https://i.stopcor.org/person/2022/4/9/vladimirzelenskij51939489510.jpeg?size=1000x1000",
  //       text: "asd",
  //       likesss: 0,
  //       likes: [],
  //       comments: 3,
  //       save: 2,
  //     },
  //     {
  //       id: "leomessi1",
  //       image:
  //         "https://www.gazeta.uz/media/img/2022/02/YRnXBo16454963010062_b.jpg",
  //       text: "asd",
  //       likesss: 0,
  //       likes: [],
  //       comments: 3,
  //       save: 2,
  //     },
  //     {
  //       id: "leomessi1",
  //       image:
  //         "https://api.delfi.lt/media-api-image-cropper/v1/ff5f7b13-6084-4558-9e82-e01b31426455.jpg?noup&w=1200&h=711&ch=0.7958&cw=1&cx=0&cy=0.0292&r=16:9&fx=0.5&fy=0.25",
  //       text: "asd",
  //       likesss: 0,
  //       likes: [],
  //       comments: 3,
  //       save: 2,
  //     },
  //     {
  //       id: "leomessi1",
  //       image:
  //         "https://www.rbc.ua/static/img/3/j/3j0a8672_id54881_650x410_4_1200x675.jpg",
  //       text: "asd",
  //       likesss: 0,
  //       likes: [],
  //       comments: 3,
  //       save: 2,
  //     },
  //     {
  //       id: "leomessi1",
  //       image:
  //         "https://s.ura.news/760/images/news/upload/news/703/883/1052703883/807222_Vladimir_Zelenskiy_stock_zelenskiy_vladimir_stock_250x0_1042.696.0.0.jpg",
  //       text: "asd",
  //       likesss: 0,
  //       likes: [],
  //       comments: 3,
  //       save: 2,
  //     },
  //   ],
  //   savePosts: [
  //     // {
  //     //   accountId: "leomessi",
  //     //   postId: "leomessi2",
  //     // },
  //     {
  //       accountId: "ufc",
  //       postId: "ufc1",
  //     },
  //     {
  //       accountId: "azov.media",
  //       postId: "azov.media3",
  //     },
  //   ],
  // },
};
